name = "my-project"
type = "webpack"
account_id = "aa83df89406ccd6b07a770d8710e3f0d"
zone_id = "41c5f96fbdf1dc5816fb6b3f3cdd8661"
route = "campinhos.pt/*"

[site]
bucket = "./public"
entry-point = "./"